# Generated by Django 2.2.4 on 2019-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0003_auto_20190812_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='category',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Assistant General Secretary', 'Assistant General Secretary'), ('Treasurer', 'Treasurer'), ('Financial Secretary', 'Financial Secretary'), ('Librarian', 'Librarian'), ('Sports Director', 'Sports Director'), ('P.R.O', 'P.R.O'), ('Social Director', 'Social Director'), ('Null', 'Null')], default='Null', max_length=120),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='reg_number',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
